version: '3.7'
name: feature-pipeline
networks:
  redpanda_network:
    external: true
services:

  trade_producer:
    build:
      context: ../trade_producer
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../trade_producer/historical.prod.env
    restart: always
#    mem_limit: 512m

  trade_to_ohlc:
    build:
      context: ../trade_to_ohlc
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../trade_to_ohlc/historical.prod.env
    restart: always
    deploy:
      replicas: 2

  topic_to_feature_store:
    build:
      context: ../topic_to_feature_store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../topic_to_feature_store/historical.prod.env
      - ../topic_to_feature_store/credentials.env
    restart: always

