name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: ''
    defaultValue: trade
    required: true
  - name: PRODUCT_IDS
    inputType: FreeText
    description: List of cryptocurrencies to get trades from Kraken
    defaultValue: '["BTC/USD","ETH/USD"]'
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Is it "live" or "historical"
    defaultValue: live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
